name: Update Docker Tags Table

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
      - development

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Docker Tags and Sizes
        run: |
          URL="https://hub.docker.com/v2/repositories/inductiva/kutu/tags/?page_size=1000"
          RESPONSE=$(curl -s "$URL")

          # Determine branch
          BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Apply filtering based on branch
          if [[ "$BRANCH" == "dev" ]]; then
            FILTER='.results[] | select(.images[0].size != null) | select(.name | endswith("_dev"))'
          else
            FILTER='.results[] | select(.images[0].size != null) | select(.name | endswith("_dev") | not)'
          fi

          # Generate the new table
          NEW_TABLE="| Tag | Size (MB) |\n"
          NEW_TABLE+="|---|---|\n"
          NEW_TABLE+=$(echo "$RESPONSE" | jq -r "$FILTER | {name, size: (.images[0].size / 1048576)}" \
            | jq -s 'sort_by(.size) | .[] | "| " + .name + " | " + (.size | tostring) + " MB |"' \
            | sed 's/"//g')

          # Create a temporary file with new content
          TEMP_FILE=$(mktemp)
          {
              echo "<!-- DOCKER-TAGS-TABLE -->"
              echo -e "$NEW_TABLE"
              echo "<!-- END-DOCKER-TAGS-TABLE -->"
          } > "$TEMP_FILE"

          # Debug: Print the generated table
          cat "$TEMP_FILE"

          # Replace the old table while keeping the placeholders
          sed -i -e '/<!-- DOCKER-TAGS-TABLE -->/,/<!-- END-DOCKER-TAGS-TABLE -->/ {
              /<!-- DOCKER-TAGS-TABLE -->/!d
              r '"$TEMP_FILE"'
              d
          }' README.md

          # Cleanup
          rm "$TEMP_FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || (git commit -m "Update Docker tags table" && git push)
